name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    # Use root/example as user/password credentials
    version: '3.1'

    env:
      DB_DATABASE: barang
      DB_USER: root
      DB_PASSWORD: "root"
      DB_HOST: localhost

  steps:
  - uses: actions/checkout@v2
  - name: Install dependencies
    run: |
        python -m pip install --upgrade pip
        pip install Pillow
        pip install tkinter
        pip install ttkthemes
        pip install pytest
        pip install mysql-connector-python
  - name: MySQL set up
    run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }}; USE ${{ env.DB_DATABASE }}; SOURCE database/barang.sql;' -u${{ env.DB_USER }} -P${{ env.DB_PASSWORD }}
  - name: Unit testing
    run: pytest -o log_cli=true
